# Server configuration for VNLib.Webserver
# Copyright (c) GitCitadel 

tcp:
  keepalive_sec: 0
  keepalive_interval_sec: 0
  max_recv_size: 655360
  max_connections: 10000
  backlog: 100
  no_delay: true
  
  #sets operating system buffer sizes
  tx_buffer: 65536
  rx_buffer: 65536

http:
  default_version: "HTTP/1.1"
  max_connections: 50000
  max_entity_size: 0
  multipart_max_buf_size: 8192
  multipart_max_size: 0
  header_buf_size: 8128
  max_request_header_count: 50
  response_header_buf_size: 16384
  max_uploads_per_request: 0
  keepalive_ms: 1000000
  recv_timeout_ms: 5000
  send_timeout_ms: 60000

  compression:
    enabled: true
    assembly: "lib/VNLib.Net.Compression/VNLib.Net.Compression.dll"
    max_size: 512000000
    min_size: 2048

vnlib.net.compression: 
  lib_path: "lib/vnlib_compress/libvn_compress.so"
  level: 1

virtual_hosts:
 - path: "root/"
   
   hostnames: 
    - "*"   #serve all hostnames

   #enables connection tracing
   trace: false

   interfaces:
    - address: "0.0.0.0"
      port: 80

      ssl: false
      certificate: ""
      private_key: ""
      client_cert_required: false
      use_os_ciphers: false

   max_execution_time_ms: 20000
   cache_default_sec: 864000
   force_port_check: false

   deny_extensions:
    - ".php"
    - ".json"
    - ".htaccess"
    - ".env"
    
   default_files:
    - "index.html"

   downstream_servers: []

   headers:
     Referrer-Policy: "strict-origin"
     X-XSS-Protection: "1; mode=block"
     X-Content-Type-Options : "nonsniff"
     X-Frame-Options: "DENY"
     Strict-Transport-Security: "max-age=4800; includeSubDomains; preload"
     Server: "GFY/0.0.1"

   cors:
     enabled: false
     deny_cors_connections: false
     allowed_authority: []

   error_files:
    - code: 404
      path: "root/404.html"

   file_http_max_age: 
     ".html": 864000
     ".css": 864000
     ".js": 864000

plugins:
  enabled: true
  hot_reload: true
  path: "plugins"
  assets: "plugins/assets"
  config_dir: "config"

logs:
  sys_log:
    enabled: false
    path: ""

  app_log:
    enabled: false
    path: ""